### ISSUE TITLE
Instalação de app alterara os scripts

### ISSUE THREAD

**Issue by ivanwhm** [Flutterando/slidy#118]
Bom dia,

Tenho a seguinte estrutura no arquivo pubspec.yaml

```
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^3.4.4995
  dio: ^3.0.8
  flutter_svg: ^0.17.1
  flutter_modular: ^0.5.2
  flutter_mobx: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.7.4
  mobx_codegen: ^1.0.2
```

Se eu executar o comando slidy install mobx para fazer a instalação do mobx, ao invés do slidy incluir a dependência no lugar correto, ele altera a linha do mobx dos scripts.

```
➜  indetectavel_app git:(feature/70) slidy install mobx                           
SUCCESS: Updated mobx in pubspec
```

Dai o pubspec.yaml fica assim:

```
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

scripts:
  mobx: ^1.0.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^3.4.4995
  dio: ^3.0.8
  flutter_svg: ^0.17.1
  flutter_modular: ^0.5.2
  flutter_mobx: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.7.4
  mobx_codegen: ^1.0.2
```

Note que a linha que ele alterou foi a linha do script ao invés de incluir nas dependências.

Obrigado!
