### ISSUE TITLE
Arquivos de Store do mobx não são gerados na criação do projeto.

### ISSUE THREAD

**Issue by luccavn** [Flutterando/slidy#135]
Quando eu crio um novo projeto usando o `slidy create` ou de dentro de um projeto já existente usando o `slidy start` os seguintes arquivos não são gerados:

- _home_controller.g.dart_ (_lib\app\modules\home\home_controller.g.dart_)
- _app_controller.g.dart_ (_lib\app\app_controller.g.dart_)

![ss_projeto_slidy](https://user-images.githubusercontent.com/17307391/79076145-107dab80-7cce-11ea-869b-1bf211bf2186.png)

Consegui gerar os arquivos manualmente através do comando:

`flutter pub run build_runner build`

Usei o **flutter_modular** como provider e o **mobx** como state manager

**Flutter 1.12.13+hotfix.8**
**Tools • Dart 2.7.0**
**Dart VM version: 2.7.2**

Dependências no pubspec.yaml:

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter
```
