### ISSUE TITLE
Slidy won't accept null or unexistent `dependencies`

### ISSUE THREAD

**Issue by mateusfccp** [Flutterando/slidy#137]
The [pubspec](https://dart.dev/tools/pub/pubspec) specification states the following about `dependencies`:

>  [Dependencies] can be omitted if your package has no dependencies.

Thus, the following file is a valid `pubspec.yaml` file:
```yaml
name: package
version: 0.01
description: Lorem ipsum

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

environment:
  sdk: ">=2.7.0 <3.0.0"
```

Inserting an empty `dependencies` should also work:
```yaml
name: package
version: 0.01
description: Lorem ipsum

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

environment:
  sdk: ">=2.7.0 <3.0.0"
```

In both cases, however, running `slidy install <package>` results in an error:
```
ERROR: No valid project found in this folder.
If you haven't created your project yet create with:

slidy create myproject

Or enter your project folder with to use slidy: 

cd myproject && slidy start

```

This error is misleading, because it both exist and it's a valid project.
