### ISSUE TITLE
Feature: scripts customizados

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/slidy#165]
Atualmente a minha seção de scripts está assim:
```yaml
scripts:
  mobx: flutter pub run build_runner build
  mobx-clean: flutter pub run build_runner build --delete-conflicting-outputs
  mobx-watch: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx-watch-clean: flutter pub run build_runner build --delete-conflicting-outputs
```
Seria possível simplificar isso para algo assim: 
```yaml
vars:
  runner: flutter pub run build_runner
scripts:
  build: $runner build
  watch: $runner watch
  build-clean: $build --delete-conflicting-outputs
  watch-clean: $watch --delete-conflicting-outputs
```

**Comment by toshiossada** [comment]
por hora vc pode fazer
scripts: 
    clean: flutter clean
    get: flutter pub get
    mobx_build: slidy run clean & slidy run get & flutter pub run build_runner build --delete-conflicting-outputs

**Comment by toshiossada** [comment]
estou fazendo a alteração, vai ficar assim

```
vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get

scripts: 
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
```


`slidy run mobx_build_clean`
