### ISSUE TITLE
Bug no slidy run

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/slidy#184]
Tenho o seguinte setup:
```yaml
vars:
  runner: flutter pub run build_runner
  clean: --delete-conflicting-outputs
scripts:
  build: $runner build
```
Se eu der o comando `slidy run build` nada acontece.
Porém se eu mudar a última linha para `build: echo $runner build` tem a saída:
```
flutter pub run build_runner build
```
Ou seja, por alguma razão o comando que deveria ser executado é "descoberto" pelo slidy mas não é executado
