### ISSUE TITLE
Bug no slidy run ao executar comando com argumentos

### ISSUE THREAD

**Issue by emersonsiega** [Flutterando/slidy#214]
Percebi uma diferença entre executar manualmente o comando `lcov --remove coverage/lcov.info '**/*.g.dart' -o coverage/lcov.info` e executar via `slidy run`.

Executando manualmente, os dados de cobertura de testes dos arquivos *.g.dart são removidos corretamente do arquivo lcov.info.
Executando via `slidy run` isso não acontece (o comando é executado normalmente, sem nenhum erro).

```yaml
scripts:
  gen_coverage: lcov --remove coverage/lcov.info '**/*.g.dart' -o coverage/lcov.info & genhtml coverage/lcov.info -o coverage/html
```

Percebi também que se eu adicionar o pattern dos arquivos a serem ignorados nas `vars`, o comando é executado corretamente.

```yaml
vars:
  ignore_files: '**/*.g.dart' 
scripts:
  gen_coverage: lcov --remove coverage/lcov.info $ignore_files -o coverage/lcov.info & genhtml coverage/lcov.info -o coverage/html
```
