### ISSUE TITLE
Slidy run "ERROR: Please, add param 'scripts' in your pubspec.yaml"

### ISSUE THREAD

**Issue by marcuslindemannrohden** [Flutterando/slidy#240]
Hey guys, since I upgraded slidy to version 3.0.0 I haven't been able to use the command "slidy run <script>" anymore.
Every time that I try, I get the error: **ERROR: Please, add param 'scripts' in your pubspec.yaml** but I do have the scripts section on my pubspec.

```
vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get

scripts:
  mobxwatch: $clean & $get & $runner watch --delete-conflicting-outputs
```
